version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#      We need all of these ports open to get browsersync to work
    ports:
      - "8002:8000"
      - "3001:3001"
      - "3000:3000"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    environment:
#      TODO: Fix this password
      POSTGRES_PASSWORD: example1
    ports:
      - "5432:5432"
    restart: always

